### ISSUE TITLE
Compiler fails with mystery DOMAIN ERROR on adverb (reduction)

### ISSUE THREAD

**Issue by bernecky** [Co-dfns/Co-dfns#432]
This failure seems to be a recent one, at least on this Ubuntu 20.10 system.

 ```
     )Clear
clear ws
      )ns ns1
#.ns1
      )cs ns1
#.ns1
      F←{+/⌽⍳⍵}
      )cs
#
      ns1.F 10
45
      ]compile ns1 modu -af=cpu
PCG
* Command Execution Failed: DOMAIN ERROR
```

The failure mode here is less than enlightening. Perhaps the compiler 
should suspend at the point of failure, to help the poor user isolate the fault?

If we remove the reduction, the compile works fine:

```

      )cs ns1
#.ns1
      ⎕vr'F'
     ∇ F←{+/⌽⍳⍵}
     ∇
      F←{⌽⍳⍵}
      F 10
9 8 7 6 5 4 3 2 1 0
      )cs 
#
      ]compile ns1 modu  -af=cpu
      )cs 
#
      modu.F 10
9 8 7 6 5 4 3 2 1 0
```

**Comment by bernecky** [comment]
Dyalog APL/S-64 Version 18.0.39660
gcc (Ubuntu 10.2.0-13ubuntu1) 10.2.0
Co-dfns commit #: 0d40d11

I suggest appending the Co-dfns commit or version number to the modu.log file.
Here are the error entries from modu.log:

```
modu.cpp:351:23: error: ‘ix’ was not declared in this scope; did you mean ‘id’?
  351 |  if(zc==w.elements()){ix[axv]=w;z.v=y(ix[0],ix[1],ix[2],ix[3]);
      |                       ^~
      |                       id
modu.cpp:357:20: error: ‘ix’ was not declared in this scope; did you mean ‘id’?
  357 |  v(i)=w-d;u(i)=s-t;ix[axv]=accum(v);z.v=y(ix[0],ix[1],ix[2],ix[3]);

```

**Comment by arcfide** [comment]
The compiler is already suspending execution at the point of failure, what you are seeing the nature of the user command interface. I am unable to replicate this bug in the current release version of Co-dfns (1.3.0) as well as the current master branch 0d40d117365964cc21830d59bbdf510df80b887b. 

Please run this using the namespace interface and send me your output so I can get some more information on this. 

-- 
Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us

**Comment by arcfide** [comment]
Looking at this error, it makes absolutely no sense. Can you copy lines 340 - 360 here from your `modu.cpp` file? 

-- 
Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us

**Comment by bernecky** [comment]
This is from the next day, and Dyalog APL 17.1, but might be close enough:

```

#include <time.h>
#include <stdint.h>
#include <stdio.h>
#include <inttypes.h>
#include <limits.h>
#include <float.h>
#include <locale>
#include <codecvt>
#include <math.h>
#include <memory>
#include <algorithm>
#include <stack>
#include <string>
#include <cstring>
#include <vector>
#include <unordered_map>
#include <arrayfire.h>
using namespace af;

#if AF_API_VERSION < 36
#error "Your ArrayFire version is too old."
#endif
#ifdef _WIN32
 #define EXPORT extern "C" __declspec(dllexport)
#elif defined(__GNUC__)
 #define EXPORT extern "C" __attribute__ ((visibility ("default")))
#else
 #define EXPORT extern "C"
#endif
#ifdef _MSC_VER
 #define RSTCT __restrict
#else
 #define RSTCT restrict
#endif
#define S struct
#define Z static
#define R return
#define this_c *this
#define RANK(lp) ((lp)->p->r)
#define TYPE(lp) ((lp)->p->t)
#define SHAPE(lp) ((lp)->p->s)
#define ETYPE(lp) ((lp)->p->e)
#define DATA(lp) ((V*)&SHAPE(lp)[RANK(lp)])
#define CS(n,x) case n:x;break;
#define DO(n,x) {I i=0,_i=(n);for(;i<_i;++i){x;}}
#define DOB(n,x) {B i=0,_i=(n);for(;i<_i;++i){x;}}
#define NM(n,nm,sm,sd,di,mf,df,ma,da) S n##_f:FN{di;mf;df;ma;da;\
 n##_f():FN(nm,sm,sd){}};
#define OM(n,nm,sm,sd,mf,df,ma,da) S n##_o:MOP{mf;df;ma;da;\
 n##_o(FN&l):MOP(nm,sm,sd,l){}};\
 S n##_k:MOK{V operator()(FN*&f,FN&l){f=new n##_o(l);}};
#define OD(n,nm,sm,sd,mf,df,ma,da) S n##_o:DOP{mf;df;ma;da;\
 n##_o(FN&l,FN&r):DOP(nm,sm,sd,l,r){}\
 n##_o(const A&l,FN&r):DOP(nm,sm,sd,l,r){}\
 n##_o(FN&l,const A&r):DOP(nm,sm,sd,l,r){}};\
 S n##_k:DOK{V operator()(FN*&f,FN&l,FN&r){f=new n##_o(l,r);}\
  V operator()(FN*&f,const A&l,FN&r){f=new n##_o(l,r);}\
  V operator()(FN*&f,FN&l,const A&r){f=new n##_o(l,r);}};
#define MT
#define DID inline array id(dim4)
#define MFD inline V operator()(A&,const A&,ENV&)
#define MAD inline V operator()(A&,const A&,ENV&,const A&)
#define DFD inline V operator()(A&,const A&,const A&,ENV&)
#define DAD inline V operator()(A&,const A&,const A&,ENV&,const A&)
#define DI(n) inline array n::id(dim4 s)
#define ID(n,x,t) DI(n##_f){R constant(x,s,t);}
#define MF(n) inline V n::operator()(A&z,const A&r,ENV&e)
#define MA(n) inline V n::operator()(A&z,const A&r,ENV&e,const A&ax)
#define DF(n) inline V n::operator()(A&z,const A&l,const A&r,ENV&e)
#define DA(n) inline V n::operator()(A&z,const A&l,const A&r,ENV&e,const A&ax)
#define SF(n,x) \
 DF(n##_f){\
  if(l.r==r.r){\
   DO(r.r,if(l.s[i]!=r.s[i])err(5))\
   z.r=l.r;z.s=l.s;const array&lv=l.v;const array&rv=r.v;x;R;}\
  if(!l.r){\
   z.r=r.r;z.s=r.s;const array&rv=r.v;array lv=tile(l.v,r.s);x;R;}\
  if(!r.r){\
   z.r=l.r;z.s=l.s;array rv=tile(r.v,l.s);const array&lv=l.v;x;R;}\
  if(l.r!=r.r)err(4);err(99);}\
 DA(n##_f){A a=l,b=r;I f=l.r>r.r;if(f){a=r;b=l;}I d=b.r-a.r;I rk=(I)cnt(ax);\
  if(rk>4)err(16);if(rk!=a.r)err(5000);D axd[4];I axv[4];ax.v.as(f64).host(axd);\
  DO(rk,if(axd[i]!=rint(axd[i]))err(11))DO(rk,axv[i]=(I)axd[i])\
  DO(rk,if(axv[i]<0||b.r<=axv[i])err(11))\
  I t[4];U8 tf[]={1,1,1,1};DO(rk,I j=axv[i];tf[j]=0;t[j]=d+i)\
  I c=0;DO(b.r,if(tf[i])t[i]=c++)A ta(1,dim4(b.r),array(b.r,t));\
  trn_c(z,ta,b,e);rho_c(b,z,e);rho_c(a,b,a,e);\
  if(f)n##_c(b,z,a,e);else n##_c(b,a,z,e);\
  gdu_c(ta,ta,e);trn_c(z,ta,b,e);}
#define PUSH(x) s.emplace(BX(x))
#define POP(f,x) x=s.top().f;s.pop()
#define EX(x) delete x
#define EF(init,ex,fun) EXPORT V ex##_dwa(lp*z,lp*l,lp*r){try{\
  A cl,cr,za;fn##init##_c(za,cl,cr,e##init);\
  cpda(cr,r);cpda(cl,l);(*(*e##init[0])[fun].f)(za,cl,cr,e##init);cpad(z,za);}\
 catch(U n){derr(n);}\
 catch(exception e){msg=mkstr(e.what());dmx.e=msg.c_str();derr(500);}}\
EXPORT V ex##_cdf(A*z,A*l,A*r){{A il,ir,iz;fn##init##_c(iz,il,ir,e##init);}\
 (*(*e##init[0])[fun].f)(*z,*l,*r,e##init);}
#define EV(init,ex,slt)
typedef enum{APLNC=0,APLU8,APLTI,APLSI,APLI,APLD,APLP,APLU,APLV,APLW,APLZ,
 APLR,APLF,APLQ}APLTYPE;
typedef long long L;typedef int I;typedef int16_t S16;typedef int8_t S8;
typedef double D;typedef unsigned char U8;typedef unsigned U;
typedef dim_t B;typedef cdouble DZ;typedef void V;typedef std::string STR;
S{U f=3;U n;U x=0;const wchar_t*v=L"Co-dfns";const wchar_t*e;V*c;}dmx;
S lp{S{L l;B c;U t:4;U r:4;U e:4;U _:13;U _1:16;U _2:16;B s[1];}*p;};
S dwa{B z;S{B z;V*(*ga)(U,U,B*,S lp*);V(*p[16])();V(*er)(V*);}*ws;V*p[4];};
S dwa*dwafns;Z V derr(U n){dmx.n=n;dwafns->ws->er(&dmx);}
EXPORT I DyalogGetInterpreterFunctions(dwa*p){
 if(p)dwafns=p;else R 0;if(dwafns->z<sizeof(S dwa))R 16;R 0;}
Z V err(U n,wchar_t*e){dmx.e=e;throw n;}Z V err(U n){dmx.e=L"";throw n;}
dim4 eshp=dim4(0,(B*)NULL);
std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>> strconv;
std::wstring msg;S BX;
typedef std::vector<BX> FRM;typedef std::vector<FRM*> ENV;
typedef std::stack<BX> STK;
S A{I r,f;dim4 s;array v;std::vector<A> nv;
 A(I r,dim4 s,array v):r(r),f(1),s(s),v(v){}
 A():r(0),f(0),s(dim4()),v(array()){}};
S FN{STR nm;I sm;I sd;FN(STR nm,I sm,I sd):nm(nm),sm(sm),sd(sd){}
 FN():nm(""),sm(0),sd(0){}
 virtual array id(dim4 s){err(16);R array();}
 virtual V operator()(A&z,const A&r,ENV&e){err(99);}
 virtual V operator()(A&z,const A&r,ENV&e,const A&ax){err(2);}
 virtual V operator()(A&z,const A&l,const A&r,ENV&e){err(99);}
 virtual V operator()(A&z,const A&l,const A&r,ENV&e,const A&ax){err(2);}};
FN MTFN;
S MOP:FN{FN&ll;
 MOP(STR nm,I sm,I sd,FN&ll):FN(nm,sm,sd),ll(ll){}};
S DOP:FN{I fl;I fr;FN&ll;A aa;FN&rr;A ww;
 DOP(STR nm,I sm,I sd,FN&l,FN&r)
  :FN(nm,sm,sd),fl(1),fr(1),ll(l),aa(A()),rr(r),ww(A()){}
 DOP(STR nm,I sm,I sd,A l,FN&r)
  :FN(nm,sm,sd),fl(0),fr(1),ll(MTFN),aa(l),rr(r),ww(A()){}
 DOP(STR nm,I sm,I sd,FN&l,A r)
  :FN(nm,sm,sd),fl(1),fr(0),ll(l),aa(A()),rr(MTFN),ww(r){}};
S MOK{virtual V operator()(FN*&f,FN&l){err(99);}};
S DOK{virtual V operator()(FN*&f,FN&l,FN&r){err(99);}
 virtual V operator()(FN*&f,const A&l,FN&r){err(99);}
 virtual V operator()(FN*&f,FN&l,const A&r){err(99);}};
S BX{A v;union{FN*f;MOK*m;DOK*d;};
 BX(){}BX(FN*f):f(f){}BX(const A&v):v(v){}BX(MOK*m):m(m){}BX(DOK*d):d(d){}};

std::wstring mkstr(const char*s){R strconv.from_bytes(s);}
I scm(FN&f){R f.sm;}I scm(const A&a){R 1;}
I scd(FN&f){R f.sd;}I scd(const A&a){R 1;}
B cnt(dim4 s){B c=1;DO(4,c*=s[i]);R c;}
B cnt(const A&a){B c=1;DO(a.r,c*=a.s[i]);R c;}
B cnt(lp*d){B c=1;DO(RANK(d),c*=SHAPE(d)[i]);R c;}
array scl(D x){R constant(x,dim4(1),f64);}
array scl(I x){R constant(x,dim4(1),s32);}
A scl(array v){R A(0,dim4(1),v);}
dtype mxt(dtype at,dtype bt){if(at==c64||bt==c64)R c64;
 if(at==f64||bt==f64)R f64;
 if(at==s32||bt==s32)R s32;if(at==s16||bt==s16)R s16;
 if(at==b8||bt==b8)R b8;err(16);R f64;}
dtype mxt(const array&a,const array&b){R mxt(a.type(),b.type());}
dtype mxt(dtype at,const A&b){R mxt(at,b.v.type());}
Z array da16(B c,dim4 s,lp*d){std::vector<S16>b(c);
 S8*v=(S8*)DATA(d);DOB(c,b[i]=v[i]);R array(s,b.data());}
Z array da8(B c,dim4 s,lp*d){std::vector<char>b(c);
 U8*v=(U8*)DATA(d);DOB(c,b[i]=1&(v[i/8]>>(7-(i%8))))
 R array(s,b.data());}
V cpad(lp*d,A&a){I t;B c=cnt(a);if(!a.f){d->p=NULL;R;}
 switch(a.v.type()){CS(c64,t=APLZ);
  CS(s32,t=APLI);CS(s16,t=APLSI);CS(b8,t=APLTI);CS(f64,t=APLD);
  default:if(c)err(16);t=APLI;}
 B s[4];DO(a.r,s[a.r-(i+1)]=a.s[i]);dwafns->ws->ga(t,a.r,s,d);
 if(c)a.v.host(DATA(d));}
V cpda(A&a,lp*d){if(d==NULL)R;if(15!=TYPE(d))err(16);if(4<RANK(d))err(16);
 dim4 s(1);DO(RANK(d),s[RANK(d)-(i+1)]=SHAPE(d)[i]);B c=cnt(d);
 switch(ETYPE(d)){
  CS(APLZ,a=A(RANK(d),s,c?array(s,(DZ*)DATA(d)):scl(0)))
  CS(APLI,a=A(RANK(d),s,c?array(s,(I*)DATA(d)):scl(0)))
  CS(APLD,a=A(RANK(d),s,c?array(s,(D*)DATA(d)):scl(0)))
  CS(APLSI,a=A(RANK(d),s,c?array(s,(S16*)DATA(d)):scl(0)))
  CS(APLTI,a=A(RANK(d),s,c?da16(c,s,d):scl(0)))
  CS(APLU8,a=A(RANK(d),s,c?da8(c,s,d):scl(0)))
  default:err(16);}}
inline I isint(D x){R x!=nearbyint(x);}
inline I isint(A x){R x.v.isinteger()||x.v.isbool()
  ||(x.v.isreal()&&allTrue<I>(x.v==trunc(x.v)));}
inline I isbool(A x){R x.v.isbool()
  ||(x.v.isreal()&&allTrue<I>(x.v==0||x.v==1));}
EXPORT A*mkarray(lp*d){A*z=new A;cpda(*z,d);R z;}
EXPORT V frea(A*a){delete a;}
EXPORT V exarray(lp*d,A*a){cpad(d,*a);}
EXPORT V afsync(){sync();}
EXPORT Window *w_new(char *k){R new Window(k);}
EXPORT I w_close(Window*w){R w->close();}
EXPORT V w_del(Window*w){delete w;}
EXPORT V w_img(lp*d,Window*w){A a;cpda(a,d);
 w->image(a.v.as(a.r==2?f32:u8));}
EXPORT V w_plot(lp*d,Window*w){A a;cpda(a,d);w->plot(a.v.as(f32));}
EXPORT V w_hist(lp*d,D l,D h,Window*w){A a;cpda(a,d);
 w->hist(a.v.as(u32),l,h);}
EXPORT V loadimg(lp*z,char*p,I c){array a=loadImage(p,c);
 A b(a.numdims(),a.dims(),a.as(s16));cpad(z,b);}
EXPORT V saveimg(lp*im,char*p){A a;cpda(a,im);
 saveImageNative(p,a.v.as(a.v.type()==s32?u16:u8));}
EXPORT V cd_sync(V){sync();}
NM(trn,"trn",0,0,MT ,MFD,DFD,MT ,MT )
trn_f trn_c;
MF(trn_f){z.r=r.r;DO(r.r,z.s[i]=r.s[r.r-(i+1)])
 switch(r.r){CS(0,z.v=r.v)CS(1,z.v=r.v)CS(2,z.v=r.v.T())
  CS(3,z.v=reorder(r.v,2,1,0))CS(4,z.v=reorder(r.v,3,2,1,0))}}
DF(trn_f){I lv[4];if(l.r>1||cnt(l)!=r.r)err(5);
 l.v.as(s32).host(lv);DO(r.r,if(lv[i]<0||lv[i]>=r.r)err(4))
 U8 f[]={0,0,0,0};DO(r.r,f[lv[i]]=1)
 U8 t=1;DO(r.r,if(t&&!f[i])t=0;else if(!t&&f[i])err(5))
 if(t){z.r=r.r;DO(r.r,z.s[r.r-(lv[i]+1)]=r.s[r.r-(i+1)])
  I s[4];DO(r.r,s[r.r-(lv[i]+1)]=r.r-(i+1))
  switch(r.r){CS(0,z.v=r.v)CS(1,z.v=r.v)
   CS(2,z.v=reorder(r.v,s[0],s[1]))
   CS(3,z.v=reorder(r.v,s[0],s[1],s[2]))
   CS(4,z.v=reorder(r.v,s[0],s[1],s[2],s[3]))}}
 else{z.r=0;DO(r.r,if(z.r<lv[i])z.r=lv[i])z.r++;DO(z.r,z.s[i]=LLONG_MAX)
  DO(r.r,I j=z.r-(lv[i]+1);I k=r.r-(i+1);if(z.s[j]>r.s[k])z.s[j]=r.s[k])
  B zs[4],rs[4];B c=1;DO(z.r,zs[i]=c;c*=z.s[i])c=1;DO(r.r,rs[i]=c;c*=r.s[i])
  c=cnt(z);array ix=iota(dim4(c),dim4(1),s32),jx=constant(0,dim4(c),s32);
  DO(r.r,I j=z.r-(lv[i]+1);I k=r.r-(i+1);jx+=rs[k]*((ix/zs[j])%z.s[j]))
  z.v=r.v(jx);}}

NM(rho,"rho",0,0,MT ,MFD,DFD,MT ,MT )
rho_f rho_c;
MF(rho_f){I sp[4]={1,1,1,1};DO(r.r,sp[r.r-(i+1)]=(I)r.s[i]);
 z.s=dim4(r.r);z.r=1;if(!cnt(z)){z.v=scl(0);R;}z.v=array(z.s,sp);}
DF(rho_f){B cr=cnt(r);B cl=cnt(l);B s[4];if(l.r>1)err(11);if(cl>4)err(16);
 l.v.as(s64).host(s);z.r=(I)cl;DO(4,z.s[i]=i>=z.r?1:s[z.r-(i+1)])B cz=cnt(z);
 if(!cz){z.v=scl(0);R;}z.v=array(cz==cr?r.v:flat(r.v)(iota(cz)%cr),z.s);}

NM(gdu,"gdu",0,0,MT ,MFD,DFD,MT ,MT )
gdu_f gdu_c;
MF(gdu_f){if(r.r<1)err(4);z.r=1;z.s=dim4(r.s[r.r-1]);
 if(!cnt(r)){z.v=r.v;R;}I c=1;DO(r.r-1,c*=(I)r.s[i]);
 array mt,a=array(r.v,c,r.s[r.r-1]);z.v=iota(z.s,dim4(1),s32);
 DO(c,sort(mt,z.v,flat(a(c-(i+1),z.v)),z.v,0,true))}
DF(gdu_f){err(16);}
NM(add,"add",1,1,DID,MFD,DFD,MT,DAD)
add_f add_c;
ID(add,0,s32)
MF(add_f){z=r;}
SF(add,z.v=lv+rv)
NM(iot,"iot",0,0,MT ,MFD,DFD,MT ,MT )
iot_f iot_c;
MF(iot_f){if(r.r>1)err(4);B c=cnt(r);if(c>4)err(10);
 if(c>1)err(16);
 z.r=1;z.s=dim4(r.v.as(s32).scalar<I>());
 z.v=z.s[0]?iota(z.s,dim4(1),s32):scl(0);}
DF(iot_f){z.r=r.r;z.s=r.s;B c=cnt(r);if(!c){z.v=scl(0);R;}
 I lc=(I)cnt(l)+1;if(lc==1){z.v=constant(0,cnt(r),s16);R;};if(l.r>1)err(16);
 array lv,ix,rv;sort(lv,ix,l.v);rv=flat(r.v);z.v=constant(0,cnt(r),s32);
 for(I h;h=lc/2;lc-=h){array t=z.v+h;replace(z.v,lv(t)>rv,t);}
 z.v=array(select(lv(z.v)==rv,ix(z.v).as(s32),(I)cnt(l)),z.s);}
OM(map,"map",1,1,MFD,DFD,MT ,MT )
MF(map_o){if(scm(ll)){ll(z,r,e);R;}
 z.r=r.r;z.s=r.s;I c=(I)cnt(z);if(!c){z.v=scl(0);R;}
 A zs;A rs=scl(r.v(0));ll(zs,rs,e);if(c==1){z.v=zs.v;R;}
 array v=array(z.s,zs.v.type());v(0)=zs.v(0);
 DO(c-1,rs.v=r.v(i+1);ll(zs,rs,e);v(i+1)=zs.v(0))z.v=v;}
DF(map_o){if(scd(ll)){ll(z,l,r,e);R;}
 if((l.r==r.r&&l.s==r.s)||!l.r){z.r=r.r;z.s=r.s;}
 else if(!r.r){z.r=l.r;z.s=l.s;}else if(l.r!=r.r)err(4);
 else if(l.s!=r.s)err(5);else err(99);I c=(I)cnt(z);
 if(!c){z.v=scl(0);R;}A zs;A rs=scl(r.v(0));A ls=scl(l.v(0));
 ll(zs,ls,rs,e);if(c==1){z.v=zs.v;R;}
 array v=array(z.s,zs.v.type());v(0)=zs.v(0);
 if(!r.r){rs.v=r.v;
  DO(c-1,ls.v=l.v(i+1);ll(zs,ls,rs,e);v(i+1)=zs.v(0);)
  z.v=v;R;}
 if(!l.r){ls.v=l.v;
  DO(c-1,rs.v=r.v(i+1);ll(zs,ls,rs,e);v(i+1)=zs.v(0);)
  z.v=v;R;}
 DO(c-1,ls.v=l.v(i+1);rs.v=r.v(i+1);ll(zs,ls,rs,e);
  v(i+1)=zs.v(0))z.v=v;}
NM(cat,"cat",0,0,MT ,MFD,DFD,MAD,DAD)
cat_f cat_c;
MF(cat_f){z.r=1;z.s=dim4(cnt(r));z.v=flat(r.v);}
MA(cat_f){B ac=cnt(ax);if(ac>1&&ax.r>1)err(4);D axv[4];ax.v.as(f64).host(axv);
 if(ac==1&&(*axv<=-1||r.r<=*axv))err(4);
 if(ac>1){I c=(I)axv[0];if(c<0)err(11);DO((I)ac,if(axv[i]!=c++)err(11))
  if(c>r.r)err(4);}
 I xt=(!ac||(ac==1&&isint(axv[0])));if(r.r==4&&xt)err(16);
 z=r;if(!xt&&ac==1)R;DO((I)ac,axv[i]=ceil(z.r-axv[i]-1))
 if(xt){z.r++;I pt=ac?(I)axv[0]:0;DO(3-pt,z.s[3-i]=z.s[2-i])z.s[pt]=1;
  z.v=moddims(z.v,z.s);R;}
 I s=(I)axv[ac-1],ei=(I)axv[0],c=1;
 DO((I)ac-1,z.s[s]*=z.s[s+i+1])DO(z.r-ei-1,z.s[s+i+1]=z.s[ei+i+1])
 z.r-=(I)ac-1;DO(4-z.r,z.s[z.r+i]=1)z.v=moddims(z.v,z.s);}
DA(cat_f){if(ax.r>1)err(4);if(cnt(ax)!=1)err(5);D ox=ax.v.as(f64).scalar<D>();
 I rk=l.r>r.r?l.r:r.r;if(ox<=-1)err(11);if(ox>=rk)err(4);
 if(l.r&&r.r&&std::abs((I)l.r-(I)r.r)>1)err(4);
 A nl=l,nr=r;D axv=rk-ox-1;I fx=(I)ceil(axv);
 if(axv!=fx){if(r.r>3||l.r>3)err(16);if(r.r&&l.r&&l.r!=r.r)err(4);
  if(l.r)cat_c(nl,l,e,ax);if(r.r)cat_c(nr,r,e,ax);
  if(!l.r&&!r.r)cat_c(nl,l,e,ax);cat_c(nr,r,e,ax);
  cat_c(z,nl,nr,e,scl(scl((I)ceil(ox))));R;}
 z.r=(l.r>=r.r)*l.r+(r.r>l.r)*r.r+(!r.r&&!l.r);
 dim4 ls=l.s;dim4 rs=r.s;
 if(!l.r){ls=rs;ls[fx]=1;}if(!r.r){rs=ls;rs[fx]=1;}
 if(r.r&&l.r>r.r){DO(3-fx,rs[3-i]=rs[3-(i+1)]);rs[fx]=1;}
 if(l.r&&r.r>l.r){DO(3-fx,ls[3-i]=ls[3-(i+1)]);ls[fx]=1;}
 DO(4,if(i!=fx&&rs[i]!=ls[i])err(5));
 DO(4,z.s[i]=(l.r>=r.r||i==fx)*ls[i]+(r.r>l.r||i==fx)*rs[i]);
 dtype mt=mxt(r.v,l.v);
 array lv=(l.r?moddims(l.v,ls):tile(l.v,ls)).as(mt);
 array rv=(r.r?moddims(r.v,rs):tile(r.v,rs)).as(mt);
 if(!cnt(l)){z.v=rv;R;}if(!cnt(r)){z.v=lv;R;}
 z.v=join(fx,lv,rv);}
DF(cat_f){if(l.r||r.r){cat_c(z,l,r,e,scl(scl((l.r>r.r?l.r:r.r)-1)));R;}
 A a,b;cat_c(a,l,e);cat_c(b,r,e);cat_c(z,a,b,e);}
NM(red,"red",0,0,DID,MT ,DFD,MT ,DAD)
ID(red,1,s32)
red_f red_c;
OM(red,"red",0,0,MFD,DFD,MAD,DAD)
DA(red_f){if(ax.r>1||cnt(ax)!=1)err(5);if(!ax.v.isinteger())err(11);
 I axv=ax.v.as(s32).scalar<I>();if(axv<0)err(11);if(axv>=r.r)err(4);
 if(l.r>1)err(4);axv=r.r-axv-1;B lc=cnt(l),rsx=r.s[axv];
 if(l.r!=0&&lc!=1&&r.r!=0&&rsx!=1&&lc!=rsx)err(5);
 array x=lc==1?tile(l.v,(I)rsx):l.v,y=rsx==1?tile(r.v,(I)lc):r.v;
 B zc=sum<B>(abs(x));z.r=r.r?r.r:1;z.s=r.s;z.s[axv]=zc;
 if(!cnt(z)){z.v=scl(0);R;}array w=where(x).as(s32);index ix[4];
 if(zc==w.elements()){ix[axv]=w;z.v=y(ix[0],ix[1],ix[2],ix[3]);
  if(zc==sum<B>(x(w)))R;dim4 sp(z.s);sp[axv]=1;
  z.v*=tile(x(w)>0,(I)sp[0],(I)sp[1],(I)sp[2],(I)sp[3]);R;}
 array i=shift(accum(abs(x(w))),1),d=shift(w,1);i(0)=0;d(0)=0;
 array v=array(zc,s32),u=array(zc,s32);v=0;u=0;
 array s=(!sign(x(w))).as(s32);array t=shift(s,1);t(0)=0;
 v(i)=w-d;u(i)=s-t;ix[axv]=accum(v);z.v=y(ix[0],ix[1],ix[2],ix[3]);
 dim4 s1(1),s2(z.s);s1[axv]=zc;s2[axv]=1;u=array(accum(u),s1);
 z.v*=tile(u,(I)s2[0],(I)s2[1],(I)s2[2],(I)s2[3]);}
DF(red_f){A x=r;if(!r.r)cat_c(x,r,e);red_c(z,l,x,e,scl(scl(x.r-1)));}
MA(red_o){if(ax.r>1)err(4);if(cnt(ax)!=1)err(5);
 if(!isint(ax))err(11);I av;ax.v.as(s32).host(&av);
 if(av<0)err(11);if(av>=r.r)err(4);av=r.r-av-1;I rc=(I)r.s[av];
 A t(r.r-1,dim4(1),r.v(0));I ib=isbool(r);
 DO(av,t.s[i]=r.s[i])DO(t.r-av,t.s[av+i]=r.s[av+i+1])
 if(!cnt(t)){t.v=scl(0);z=t;R;}
 if(!rc){t.v=ll.id(t.s);z=t;R;}
 if(1==rc){t.v=array(r.v,t.s);z=t;R;}
 if("add"==ll.nm&&ib){t.v=count(r.v,av).as(s32);z=t;R;}
 if("add"==ll.nm){t.v=moddims(sum(r.v.as(f64),av),t.s);z=t;R;}
 if("mul"==ll.nm){t.v=moddims(product(r.v.as(f64),av),t.s);z=t;R;}
 if("min"==ll.nm){t.v=moddims(min(r.v,av),t.s);z=t;R;}
 if("max"==ll.nm){t.v=moddims(max(r.v,av),t.s);z=t;R;}
 if("and"==ll.nm&&ib){t.v=moddims(allTrue(r.v,av),t.s);z=t;R;}
 if("lor"==ll.nm&&ib){t.v=moddims(anyTrue(r.v,av),t.s);z=t;R;}
 if("neq"==ll.nm&&ib){t.v=moddims((1&sum(r.v,0)).as(b8),t.s);z=t;R;}
 map_o mfn_c(ll);af::index x[4];x[av]=rc-1;
 t.v=moddims(r.v(x[0],x[1],x[2],x[3]),t.s);
 DO(rc-1,x[av]=rc-i-2;
  mfn_c(t,A(t.r,t.s,moddims(r.v(x[0],x[1],x[2],x[3]),t.s)),t,e))
 z=t;}
MF(red_o){A x=r;if(!r.r)cat_c(x,r,e);
 red_o mfn(ll);mfn(z,x,e,scl(scl(x.r-1)));}
DA(red_o){if(ax.r>1)err(4);if(cnt(ax)!=1)err(5);
 if(!isint(ax))err(11);I av;ax.v.as(s32).host(&av);
 if(av<0)err(11);if(av>=r.r)err(4);av=r.r-av-1;
 if(l.r>1)err(4);if(cnt(l)!=1)err(5);
 if(!isint(l))err(11);I lv=l.v.as(s32).scalar<I>();I rc=(I)r.s[av]+1;
 if(rc<lv)err(5);rc=(I)(rc-abs(lv));map_o mfn_c(ll);
 A t(r.r,r.s,scl(0));t.s[av]=rc;if(!cnt(t)){z=t;R;}
 if(!lv){t.v=ll.id(t.s);z=t;R;}seq rng(rc);af::index x[4];
 if(lv>=0){x[av]=rng+((D)lv-1);t.v=r.v(x[0],x[1],x[2],x[3]);
  DO(lv-1,x[av]=rng+(D)(lv-i-2);
   mfn_c(t,A(t.r,t.s,r.v(x[0],x[1],x[2],x[3])),t,e))
 }else{x[av]=rng;t.v=r.v(x[0],x[1],x[2],x[3]);
  DO(abs(lv)-1,x[av]=rng+(D)(i+1);
   mfn_c(t,A(t.r,t.s,r.v(x[0],x[1],x[2],x[3])),t,e))}
 z=t;}
DF(red_o){if(!r.r)err(4);
 red_o mfn_c(ll);mfn_c(z,l,r,e,scl(scl(r.r-1)));}
S fn0_f:FN{MFD;DFD;fn0_f():FN("fnfn0",0,0){};};
fn0_f fn0_c;MF(fn0_f){fn0_c(z,A(),r,e);}
S fn12_f:FN{MFD;DFD;fn12_f():FN("fnfn12",0,0){};};
fn12_f fn12_c;MF(fn12_f){fn12_c(z,A(),r,e);}

ENV e0(1);I is0=0;
DF(fn0_f){if(is0)R;I fd=0;STK s;e[0]=new FRM(1);
 PUSH(&fn12_c);
 (*e[fd])[0]=s.top();
 s.pop();
 is0=1;}


DF(fn12_f){FRM*of=NULL;I fd=1;try{STK s;
FRM f(0);if(e.size()<=fd)e.resize(fd+1);of=e[fd];e[fd]=&f;
 PUSH(r);
 PUSH(&iot_c);
 {A z,x;FN*f;POP(f,f);POP(v,x);(*f)(z,x,e);PUSH(z);}
 PUSH(&add_c);
 PUSH(new red_k());
 {FN*f,*g;MOK*o;POP(m,o);POP(f,g);(*o)(f,*g);EX(o);PUSH(f);}
 {A z,x;FN*f;POP(f,f);POP(v,x);(*f)(z,x,e);PUSH(z);}
 POP(v,z);z.f=1;e[fd]=of;R;
 }catch(U x){e[fd]=of;throw x;}
 catch(exception x){e[fd]=of;throw x;}}
EF(0,F,0)

```

**Comment by arcfide** [comment]
Okay, I think I know what's going one. 

-- 
Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us

**Comment by arcfide** [comment]
I just pushed up PR #438 . Could you take a look at this and see if it fixes your issues here?

**Comment by bernecky** [comment]
No joy: F←{⌽⍳⍵} compiles and executes properly, but F←{+/⌽⍳⍵} merely
produces DOMAIN ERROR during the compile:
```

          ]compile ns1 modu -af=cpu
PCG
* Command Execution Failed: DOMAIN ERROR
      ⎕nl 9
ns1
      )cs ns1
#.ns1
      )fns
F       
      )vars
      ⎕nl 9
      F 20
190
      ⎕vr'F'
     ∇ F←{+/⌽⍳⍵}
     ∇
```

**Comment by arcfide** [comment]
Can you send me the log file? 

-- 
Aaron W. Hsu | arcfide@sacrideo.us | http://www.sacrideo.us

**Comment by arcfide** [comment]
Actually, in addition to the log file, can you please ensure that you are running off the right PR branch for testing this?

**Comment by bernecky** [comment]
This with the gcc-warnings branch. Here's the log file:

This version still gets DOMAIN ERROR.

[modu.log](https://github.com/Co-dfns/Co-dfns/files/5778639/modu.log)

**Comment by arcfide** [comment]
The gcc-warnings branch is for #431 , not for this issue. See above PR #438 for testing this issue.

**Comment by bernecky** [comment]
Using the index-namespace branch:

The DOMAIN ERROR has gone away, and modu.F 20 now executes correctly. However, the compilation
still produces many warnings about modu.cpp.

[modu.log](https://github.com/Co-dfns/Co-dfns/files/5781386/modu.log)

**Comment by arcfide** [comment]
Okay, great, most of these warnings should go away once we have your two issues merged into master, at that point, we'll want to see if all is good. Standby for a new patch release.

**Comment by bernecky** [comment]
I just did a pull/checkout of the master branch, giving me commit 1b87a31.
]compile now completes, but with warnings*, starting with:
```

     )clear
clear ws
      )ns ns1
#.ns1
      )cs ns1
#.ns1
      F←{+/⌽⍳⍵}
      )cs
#
      ]compile ns1 modu -af=cpu
PCG
 modu.cpp: In member function ‘virtual V fn14_f::operator()(A&, CA&, CA&, ENV&)’:                            
 modu.cpp:91:15: warning: deleting object of polymorphic class type ‘MOK’ which has non-virtual destructor mi
    91 | #define EX(x) delete x                          
```
[modu.log](https://github.com/Co-dfns/Co-dfns/files/5787526/modu.log)

There is another warning or so near the end of the log file, too.

* The session log spills to the tune of over 1200 lines. Perhaps (a) do a ⎕pw↑⍤1⊢modu.log, and/or a
pointer to the log, e.g., "See /tmp/reducetest/modu.log" for details.

**Comment by arcfide** [comment]
I think hiding the session log would defeat the purpose of having it in the first place. Long warnings should create frictions. Hiding them is too easy to ignore.

**Comment by bernecky** [comment]
Good point. I think that a lot of my frustration here is with the way that RIDE handles linux text (with NL characters) in its
session log. I think I'll go pester the RIDErs to fix it.

**Comment by bernecky** [comment]
All good now. Here it is with your commit:  fe9fc119ea15fd6ad615d7ad43ef012bef191e1b

Thanks!

P.S.: In other news, RIDErs have been pestered, and a posse is being formed...

```
  )clear
clear ws
      )ns ns1
#.ns1
      )cs ns1
#.ns1
        F←{+/⌽⍳⍵}
      F 100
4950
     )cs
#
    ]compile ns1 modu -af=cpu
PCG
      ⎕nl 9
modu
ns1 
      ns1.F 100
4950
      modu.F 100
4950
```
I also tried your missing function test, just in case:

```
      ⎕ex'ns1.F'
      )cs
#
    ]compile ns1 modu -af=cpu
PCG
 modu.cpp:122:18: warning: ‘V derr(U)’ defined but not used [-Wunused-function] 
   122 | S dwa*dwafns;Z V derr(U n){dmx.n=n;dwafns->ws->er(&dmx);}              
       |                  ^~~~                                                  
```
